# Generated by Django 4.0 on 2022-01-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('visitantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Excursiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=25)),
                ('duracion', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
